server:
  port: 8223
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: parking-main
          uri: lb:http://parking-main
          predicates:
            - Path=/smart/parking/**
          filters:
            - AuthenticationFilter
        - id: smart-finance
          uri: lb:http://smart-finance
          predicates:
            - Path=/smart/finance/**
          filters:
            - AuthenticationFilter
        - id: smart-user
          uri: lb:http://smart-user
          predicates:
            - Path=/smart/user/**
          filters:
            - AuthenticationFilter
security.jwt.token.secret-key: WMT0217380917746215000000000000000111111998KK
